[package]
name = "rfesi"
version = "0.12.0"
authors = ["Celeo <mattboulanger@fastmail.com>"]
edition = "2021"
description = "Rust API for EVE Online's ESI"
readme = "README.md"
homepage = "https://github.com/celeo/rfesi"
repository = "https://github.com/celeo/rfesi"
documentation = "https://docs.rs/rfesi"
license = "MIT OR Apache-2.0"
exclude = [".github"]
keywords = ["eve", "eve-online", "esi"]
categories = ["api-bindings"]

[dependencies]
alcoholic_jwt = { version = "4091.0.0", optional = true }
base64 = "0.13"
chrono = "0.4.11"
http = "0.2.1"
log = "0.4.8"
rand = { version = "0.8.5", optional = true }
reqwest = { version = "0.11.0", features = ["json"] }
serde = { version = "1.0.113", features = ["derive"] }
serde_json = "1.0.55"
thiserror = "1.0.20"

[dev-dependencies]
mockito = "0.31"

[features]
default = ["random_state", "validate_jwt"]
random_state = ["dep:rand"]
validate_jwt = ["dep:alcoholic_jwt"]
