[package]
name = "rfesi"
version = "0.1.0"
authors = ["Celeo <mattboulanger@fastmail.com>"]
edition = "2018"
description = "Rust API for the EVE online ESI"
readme = "README.md"
homepage = "https://github.com/celeo/rfesi"
repository = "https://github.com/celeo/rfesi"
license = "MIT OR Apache-2.0"
exclude = [
  ".github"
]
keywords = [
]
categories = [
]

[dependencies]
http = "0.2.1"
log = "0.4.8"
reqwest = { version = "0.10.6", features = ["json"] }
serde = { version = "1.0.113", features = ["derive"] }
serde_json = "1.0.55"
thiserror = "1.0.20"

[dev-dependencies]
mockito = "0.25.2"
