[package]
name = "rfesi"
version = "0.10.0"
authors = ["Celeo <mattboulanger@fastmail.com>"]
edition = "2018"
description = "Rust API for EVE Online's ESI"
readme = "README.md"
homepage = "https://github.com/celeo/rfesi"
repository = "https://github.com/celeo/rfesi"
documentation = "https://docs.rs/rfesi"
license = "MIT OR Apache-2.0"
exclude = [
  ".github"
]
keywords = [
  "eve",
  "eve-online",
  "esi"
]
categories = [
  "api-bindings"
]

[dependencies]
base64 = "0.12.3"
chrono = "0.4.11"
http = "0.2.1"
log = "0.4.8"
reqwest = { version = "0.11.0", features = ["json"] }
serde = { version = "1.0.113", features = ["derive"] }
serde_json = "1.0.55"
thiserror = "1.0.20"

[dev-dependencies]
mockito = "0.25.2"
tokio = { version = "0.2.21", features = ["macros", "rt-threaded"] }
