//! Endpoint groups

mod alliance;
pub use alliance::*;
mod assets;
pub use assets::*;
mod bookmarks;
pub use bookmarks::*;
mod calendar;
pub use calendar::*;
mod character;
pub use character::*;
mod clones;
pub use clones::*;
mod contacts;
pub use contacts::*;
mod contracts;
pub use contracts::*;
mod corporation;
pub use corporation::*;
mod dogma;
pub use dogma::*;
mod faction_warfare;
pub use faction_warfare::*;
mod fittings;
pub use fittings::*;
mod fleets;
pub use fleets::*;
mod incursions;
pub use incursions::*;
mod industry;
pub use industry::*;
mod insurance;
pub use insurance::*;
mod killmails;
pub use killmails::*;
mod location;
pub use location::*;
mod loyalty;
pub use loyalty::*;
mod mail;
pub use mail::*;
mod market;
pub use market::*;
mod opportunities;
pub use opportunities::*;
mod planetary_interaction;
pub use planetary_interaction::*;
mod routes;
pub use routes::*;
mod search;
pub use search::*;
mod skills;
pub use skills::*;
mod sovereignty;
pub use sovereignty::*;
mod status;
pub use status::*;
mod universe;
pub use universe::*;
mod user_interface;
pub use user_interface::*;
mod wallet;
pub use wallet::*;
mod wars;
pub use wars::*;
